// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAPzx1k0UvriOddSMJ42DqmL3XCZYIYzQ',
    appId: '1:342300879153:web:1cffbb15ee7d46f75ee810',
    messagingSenderId: '342300879153',
    projectId: 'reemverse-prod-24',
    authDomain: 'reemverse-prod-24.firebaseapp.com',
    storageBucket: 'reemverse-prod-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXGklVtX-Z7Pm8VIO1nBg_3y9H9G3jTIU',
    appId: '1:342300879153:android:c5f2f97ab30a2ab35ee810',
    messagingSenderId: '342300879153',
    projectId: 'reemverse-prod-24',
    storageBucket: 'reemverse-prod-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRU9GbVdoNUdwzhwWcmRHOM9HnH8_xGEY',
    appId: '1:342300879153:ios:52a682d1c70692665ee810',
    messagingSenderId: '342300879153',
    projectId: 'reemverse-prod-24',
    storageBucket: 'reemverse-prod-24.appspot.com',
    iosClientId: '342300879153-b1ujv61c6jq8c7bbf89r59impirbjb05.apps.googleusercontent.com',
    iosBundleId: 'com.example.reemVerseRebuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRU9GbVdoNUdwzhwWcmRHOM9HnH8_xGEY',
    appId: '1:342300879153:ios:52a682d1c70692665ee810',
    messagingSenderId: '342300879153',
    projectId: 'reemverse-prod-24',
    storageBucket: 'reemverse-prod-24.appspot.com',
    iosClientId: '342300879153-b1ujv61c6jq8c7bbf89r59impirbjb05.apps.googleusercontent.com',
    iosBundleId: 'com.example.reemVerseRebuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAPzx1k0UvriOddSMJ42DqmL3XCZYIYzQ',
    appId: '1:342300879153:web:89580e8b7fc89d5e5ee810',
    messagingSenderId: '342300879153',
    projectId: 'reemverse-prod-24',
    authDomain: 'reemverse-prod-24.firebaseapp.com',
    storageBucket: 'reemverse-prod-24.appspot.com',
  );

}