-- ========== TABLES ==========

-- Profiles Table
create table if not exists profiles (
  id uuid primary key,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamptz default now(),
  bio text,
  phone text,
  note text
);

-- Posts Table
create table if not exists posts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  user_id uuid references profiles(id),
  title text,
  content text,
  image_url text
);

-- Marketplace Table
create table if not exists marketplace (
  id uuid primary key default uuid_generate_v4(),
  created_at timestamptz default now(),
  user_id uuid references profiles(id),
  title text,
  description text,
  price numeric,
  image_url text
);

-- Notifications Table
create table if not exists notifications (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references profiles(id),
  title text,
  body text,
  is_read boolean default false,
  created_at timestamptz default now()
);

-- Messages Table
create table if not exists messages (
  id uuid primary key default uuid_generate_v4(),
  sender_id uuid references profiles(id),
  receiver_id uuid references profiles(id),
  content text,
  is_read boolean default false,
  created_at timestamptz default now()
);

-- Post Likes Table
create table if not exists post_likes (
  id uuid primary key default uuid_generate_v4(),
  post_id bigint references posts(id) on delete cascade,
  user_id uuid references profiles(id) on delete cascade,
  created_at timestamptz default now(),
  unique(post_id, user_id)
);

-- Posts Details Table (for LandingPage Posts)
CREATE TABLE IF NOT EXISTS post_details (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  post_id bigint REFERENCES posts(id) ON DELETE CASCADE,
  content text,
  images text[],
  created_at timestamptz DEFAULT now()
);

-- Marketplace Details Table (for Marketplace Products)
CREATE TABLE IF NOT EXISTS marketplace_details (
  id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  product_id uuid REFERENCES marketplace(id) ON DELETE CASCADE,
  description text,
  additional_images text[],
  seller_notes text,
  created_at timestamptz DEFAULT now()
);

-- ========== ENABLE RLS ==========
alter table profiles enable row level security;
alter table posts enable row level security;
alter table marketplace enable row level security;
alter table notifications enable row level security;
alter table messages enable row level security;
alter table post_likes enable row level security;
alter table post_details enable row level security;
alter table marketplace_details enable row level security;

-- ========== POLICIES ==========

-- Profiles Policies
drop policy if exists "Allow users to update their own profile" on profiles;
drop policy if exists "Allow users to view all profiles" on profiles;
drop policy if exists "Allow users to insert their own profile" on profiles;

create policy "Allow users to update their own profile"
  on profiles for update using (auth.uid() = id);

create policy "Allow users to view all profiles"
  on profiles for select using (true);

create policy "Allow users to insert their own profile"
  on profiles for insert with check (auth.uid() = id);

-- Posts Policies
drop policy if exists "Allow anyone to read posts" on posts;
drop policy if exists "Allow users to insert posts" on posts;
drop policy if exists "Allow users to update their own posts" on posts;
drop policy if exists "Allow users to delete their own posts" on posts;

create policy "Allow anyone to read posts"
  on posts for select using (true);

create policy "Allow users to insert posts"
  on posts for insert with check (auth.uid() = user_id);

create policy "Allow users to update their own posts"
  on posts for update using (auth.uid() = user_id);

create policy "Allow users to delete their own posts"
  on posts for delete using (auth.uid() = user_id);

-- Marketplace Policies
drop policy if exists "Allow anyone to view marketplace" on marketplace;
drop policy if exists "Allow users to insert items" on marketplace;
drop policy if exists "Allow users to update their own items" on marketplace;
drop policy if exists "Allow users to delete their own items" on marketplace;

create policy "Allow anyone to view marketplace"
  on marketplace for select using (true);

create policy "Allow users to insert items"
  on marketplace for insert with check (auth.uid() = user_id);

create policy "Allow users to update their own items"
  on marketplace for update using (auth.uid() = user_id);

create policy "Allow users to delete their own items"
  on marketplace for delete using (auth.uid() = user_id);

-- Notifications Policies
drop policy if exists "Users can read their notifications" on notifications;
create policy "Users can read their notifications"
  on notifications for select using (user_id = auth.uid());

-- Messages Policies
drop policy if exists "Allow users to insert messages" on messages;
drop policy if exists "Allow users to update their own sent messages" on messages;
drop policy if exists "Allow users to delete their own sent messages" on messages;
drop policy if exists "Allow users to view their messages" on messages;

create policy "Allow users to insert messages"
  on messages for insert with check (auth.uid() = sender_id);

create policy "Allow users to update their own sent messages"
  on messages for update using (auth.uid() = sender_id);

create policy "Allow users to delete their own sent messages"
  on messages for delete using (auth.uid() = sender_id);

create policy "Allow users to view their messages"
  on messages for select using (auth.uid() = sender_id OR auth.uid() = receiver_id);

-- Post Likes Policies
drop policy if exists "Allow users to view post likes" on post_likes;
drop policy if exists "Allow users to insert post likes" on post_likes;
drop policy if exists "Allow users to delete their own post likes" on post_likes;

create policy "Allow users to view post likes"
  on post_likes for select using (true);

create policy "Allow users to insert post likes"
  on post_likes for insert with check (auth.uid() = user_id);

create policy "Allow users to delete their own post likes"
  on post_likes for delete using (auth.uid() = user_id);

-- Post Details Policies
drop policy if exists "Allow all users to view post details" on post_details;
drop policy if exists "Allow authors manage own post details" on post_details;

create policy "Allow all users to view post details"
  on post_details for select using (true);

create policy "Allow authors manage own post details"
  on post_details for all using (
    post_id in (select id from posts where user_id = auth.uid())
  );

-- Marketplace Details Policies
drop policy if exists "Allow all users to view marketplace details" on marketplace_details;
drop policy if exists "Allow sellers manage own marketplace details" on marketplace_details;

create policy "Allow all users to view marketplace details"
  on marketplace_details for select using (true);

create policy "Allow sellers manage own marketplace details"
  on marketplace_details for all using (
    product_id in (select id from marketplace where user_id = auth.uid())
  );

-- ========== END ==========

-- Enable RLS and allow profile owner to update own profile
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow profile owner to update own profile"
  ON profiles
  FOR UPDATE
  USING (auth.uid() = id);

