name: Supabase DB Migration

on:
  push:
    paths:
      - 'supabase_schema/init_schema.sql'
      - '.github/workflows/db-migration.yml'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Supabase CLI
        run: |
          npm install -g supabase

      - name: Run migration SQL
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          supabase db reset --project-ref $SUPABASE_PROJECT_ID --password $SUPABASE_DB_PASSWORD --db-url "postgresql://postgres:$SUPABASE_DB_PASSWORD@db.$SUPABASE_PROJECT_ID.supabase.co:5432/postgres" --file supabase_schema/init_schema.sql
