name: Build iOS Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      FLUTTER_VERSION: '3.19.6'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod install && cd ..
        
      - name: Setup iOS certificates
        uses: apple-actions/import-codesigning-certs@v1
        with:
          p12-file-base64: ${{ secrets.IOS_P12_CERTIFICATE }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
          keychain: build.keychain
          keychain-password: ''

      - name: Setup provisioning profile
        uses: apple-actions/download-provisioning-profiles@v1
        with:
          bundle-id: 'com.reemverse.app'
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Increment build number
        run: |
          cd ios
          agvtool new-version -all ${{ github.run_number }}
          cd ..

      - name: Build IPA
        run: |
          flutter build ipa --release \
            --export-options-plist=ios/Runner/ExportOptions.plist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ipa-build
          path: build/ios/ipa/*.ipa
          retention-days: 5

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight@v1
        with:
          app-path: build/ios/ipa/*.ipa
          api-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          distribute-external: true
          notify-external-testers: true