name: Build iOS Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    env:
      XCODE_VERSION: '15.2'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Flutter Clean
        run: flutter clean
        
      - name: Setup keychain
        run: |
          security create-keychain -p '' build.keychain
          security list-keychains -d user -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p '' build.keychain
          security set-keychain-settings build.keychain

      - name: Setup iOS certificates
        uses: apple-actions/import-codesigning-certs@v1
        with:
          p12-file-base64: ${{ secrets.IOS_P12_CERTIFICATE }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
          keychain: build.keychain
          keychain-password: ''

      - name: Setup provisioning profile
        uses: apple-actions/download-provisioning-profiles@v1
        with:
          bundle-id: 'com.reemverse.app'
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Validate Xcode setup
        run: flutter doctor -v

      - name: Build IPA
        run: flutter build ipa --release --export-method app-store

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight@v1
        with:
          ipa-path: build/ios/ipa/*.ipa
          api-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          key-id: ${{ secrets.APPSTORE_KEY_ID }}
          expire-build-submitted-date: 30