name: Flutter iOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter 3.32.4
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: stable
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Build iOS (debug)
        run: flutter build ios --debug --no-codesign
      - name: Archive iOS (release)
        run: flutter build ios --release --no-codesign
