name: Build iOS Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # أو أي إصدار مشروعك

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ipa --release

      - name: Upload to TestFlight
        uses: apple-actions/upload-app-store-build@v1
     with:
      apiKey: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      issuerId: ${{ secrets.APPSTORE_ISSUER_ID }}
      keyId: ${{ secrets.APPSTORE_KEY_ID }}

