name: Build iOS Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.22.1"

    - name: Install Flutter dependencies
      run: flutter pub get

    - name: Clean project
      run: flutter clean

    - name: Build iOS (release, no codesign)
      run: flutter build ios --release --no-codesign

    - name: Archive .ipa
      run: |
        mkdir -p output
        cd build/ios/iphoneos
        /usr/bin/xcrun \
          -sdk iphoneos \
          PackageApplication -v Runner.app \
          -o "$GITHUB_WORKSPACE/output/Runner.ipa"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ReemVerse-iOS
        path: output/Runner.ipa
