name: iOS Build & TestFlight

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS & Upload
    runs-on: macos-latest
    
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Apple Certificate
        uses: apple-actions/import-codesigning-certs@v1
        with:
          p12-file-base64: ${{ secrets.IOS_P12_CERTIFICATE }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
          keychain-password: ''
          
      - name: Install Provisioning Profile
        uses: apple-actions/download-provisioning-profiles@v1
        with:
          bundle-id: 'com.reemverse.app'
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true
          architecture: x64
          
      - name: Install Flutter Dependencies
        run: flutter pub get
        
      - name: Install CocoaPods Dependencies
        working-directory: ios
        run: |
          pod repo update
          pod install
          
      - name: Set Build Number
        run: |
          cd ios
          LATEST_BUILD=`xcrun agvtool what-version -terse`
          NEW_BUILD=$((LATEST_BUILD + 1))
          agvtool new-version -all $NEW_BUILD
          
      - name: Build iOS App
        run: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            clean archive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="${{ secrets.APPLE_TEAM_ID }}" \
            PROVISIONING_PROFILE_SPECIFIER="${{ secrets.PROVISIONING_PROFILE_NAME }}"

      - name: Create IPA
        run: |
          cd ios
          xcodebuild \
            -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist exportOptions.plist
            
      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ios/build/ios/ipa/Runner.ipa
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ipa-file
          path: ios/build/ios/ipa/Runner.ipa
